
const products=window.CHARGE_PRODUCTS;
const labels={1131:['Enerfill FP21','پاوربانک','برای بررسی یک گزینه جمع‌وجور'],247:['Bipow 2 Pro','پاوربانک','برای بررسی ظرفیت بیشتر'],244:['Blade H1','پاوربانک','برای گوشی و لپ‌تاپ‌های سازگار'],1025:['Palm 20W','شارژر','یک گزینه برای بررسی شارژ تک‌دستگاه'],238:['Cube Pro 65W','شارژر','برای بررسی شارژ چند دستگاه'],240:['Enerfill FE11','شارژر','برای بررسی نیاز به توان بیشتر'],16:['Power Combo','شارژر رومیزی','برای بررسی روی میز کار']};
const bankIds=[1131,247,244];const getProduct=id=>products.find(p=>p.id===id);
function productCard(p){const t=labels[p.id];return '<article class="product-card enter"><div class="product-image"><img loading="lazy" src="assets/'+p.id+'.webp" alt="'+t[0]+'" width="320" height="320"></div><span class="kind">Baseus · '+t[1]+'</span><h3>'+t[0]+'</h3><p>'+t[2]+'</p><a href="'+p.url+'" target="_blank" rel="noopener">مشخصات و قیمت روز</a></article>'}
function renderProducts(filter='all'){document.querySelector('#product-grid').innerHTML=products.filter(p=>filter==='all'||(filter==='powerbank'?bankIds.includes(p.id):!bankIds.includes(p.id))).map(productCard).join('');document.querySelectorAll('[data-filter]').forEach(b=>{const on=b.dataset.filter===filter;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)})}
renderProducts();document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>renderProducts(b.dataset.filter));
const wizard=document.querySelector('#wizard');const initial=wizard.innerHTML;
let state={step:1,need:null,device:null,priority:null};
const devices=[['iphone-lightning','آیفون ۸ تا ۱۴','درگاه Lightning'],['iphone-usbc','آیفون ۱۵ و جدیدتر','درگاه USB-C'],['samsung','سامسونگ','مدل دقیق روی سرعت اثر دارد'],['xiaomi','شیائومی / پوکو','شارژ توربو به ترکیب سازگار نیاز دارد'],['other','گوشی دیگر / نمی‌دانم','با راهنمای عمومی شروع کنیم'],['laptop','لپ‌تاپ یا تبلت','توان و ورودی دستگاه مهم است']];
const priorities={powerbank:[['light','سبک و همراه','برای رفت‌وآمد روزانه'],['capacity','شارژ ذخیره بیشتر','برای روزهای طولانی‌تر'],['reuse','خرید به‌اندازه نیاز','اول وسایل فعلی‌ام را بررسی کنم']],charger:[['single','فقط یک دستگاه','شارژ ساده در خانه یا محل کار'],['multi','چند دستگاه با هم','گوشی، تبلت یا لپ‌تاپ'],['reuse','برای شارژ پاوربانک','شاید کلگی فعلی کافی باشد']],both:[['light','رفت‌وآمد روزانه','یک ترکیب ساده و قابل حمل'],['multi','چند دستگاه','نیاز به بررسی توان هم‌زمان'],['reuse','خرج اضافه نکنم','اول لوازمی که دارم']]};
function rail(){document.querySelectorAll('.rail-steps span').forEach((el,i)=>el.classList.toggle('active',i===Math.min(state.step-1,2)))}
function focusWizard(){wizard.classList.remove('enter');void wizard.offsetWidth;wizard.classList.add('enter');wizard.querySelector('h3')?.focus({preventScroll:true});rail()}
function options(rows,key){return '<div class="device-options">'+rows.map(r=>'<button class="option" data-'+key+'="'+r[0]+'">'+r[1]+'<small>'+r[2]+'</small></button>').join('')+'</div>'}
function renderWizard(){if(state.step===1)wizard.innerHTML=initial;
if(state.step===2)wizard.innerHTML='<span class="step-label">قدم ۲ از ۳</span><h3 tabindex="-1">بیشتر برای چه دستگاهی؟</h3>'+options(devices,'device')+'<div class="wizard-actions"><button class="back" data-back="1">برگشت</button><span class="quiet">لازم نیست مشخصات فنی را حفظ باشی.</span></div>';
if(state.step===3)wizard.innerHTML='<span class="step-label">قدم ۳ از ۳</span><h3 tabindex="-1">چه چیزی برات مهم‌تره؟</h3>'+options(priorities[state.need],'priority')+'<div class="wizard-actions"><button class="back" data-back="2">برگشت</button></div>';
if(state.step===4)renderResult();focusWizard()}
function mini(id){const p=getProduct(id);return '<a class="mini-product" href="'+p.url+'" target="_blank" rel="noopener"><img src="assets/'+id+'.webp" alt="" width="65" height="75"><span><b dir="ltr">'+labels[id][0]+'</b><small>دیدن مشخصات و قیمت روز</small></span></a>'}
function resultData(){
const device=state.device;
const wires={
'iphone-lightning':['کابل متناسب با Lightning','برای اتصال به خروجی USB-C، کابل USB-C به Lightning سازگار لازم داری. کابل USB-C متصل به بعضی پاوربانک‌ها مستقیم به این آیفون‌ها وصل نمی‌شود.'],
'iphone-usbc':['اتصال USB-C به USB-C','کابل و منبع شارژ سازگار انتخاب کن. توان بالاتر روی جعبه، به‌تنهایی سرعت بیشتری برای هر مدل آیفون تضمین نمی‌کند.'],
'samsung':['برای سوپرفست، مدل دقیق مهم است','اگر گوشی از Super Fast Charging پشتیبانی می‌کند، پشتیبانی شارژر یا پاوربانک از PD/PPS و شرایط کابل همان مدل را بررسی کن. همه گوشی‌های سامسونگ شرایط یکسانی ندارند.'],
'xiaomi':['توربو را فقط از روی وات انتخاب نکن','حالت‌های سریع اختصاصی شیائومی به گوشی، شارژر و کابل سازگار وابسته‌اند. روی یک پاوربانک عمومی، رسیدن به همان سرعت شارژر اصلی را قطعی فرض نکن.'],
'other':['اول درگاه گوشی را بشناسیم','نام مدل در بخش «درباره تلفن» است. شکل درگاه و مشخصات شارژ همان مدل را بررسی کن؛ تا آن زمان سرعت مشخصی برای یک محصول وعده نمی‌دهیم.'],
'laptop':['اول پشتیبانی شارژ از USB-C را بررسی کن','داشتن USB-C به‌تنهایی کافی نیست. پشتیبانی شارژ ورودی، توان موردنیاز و کابل مناسب لپ‌تاپ یا تبلت را از راهنمای همان مدل بررسی کن.']
};
const reuse=state.priority==='reuse';const multi=state.priority==='multi';
const heading=reuse?'قبل از خرید، همین وسایل را بررسی کن.':multi?'توان هم‌زمان را در نظر بگیر.':state.priority==='capacity'?'ظرفیت بیشتر، با توجه به وزن.':'یک انتخاب ساده برای استفاده روزانه.';
const lead=reuse?'اگر کلگی فعلی با ورودی پاوربانک یا گوشی سازگار است و سرعتش برایت کافی است، لازم نیست فقط برای عدد وات بالاتر عوضش کنی.':multi?'عدد بزرگ روی شارژر معمولاً تمام داستان نیست؛ هنگام اتصال چند دستگاه، جدول تقسیم توان پورت‌ها را بررسی کن.':state.priority==='capacity'?'ظرفیت بیشتر می‌تواند ذخیره بیشتری بدهد؛ اما وزن، انرژی قابل تحویل و مصرف گوشی هم روی تجربه اثر دارند. تعداد شارژ را قطعی فرض نکن.':'اگر بیشتر بیرون از خانه هستی، وزن و اندازه هم در کنار ظرفیت مهم‌اند. فقط به عدد بزرگ‌تر روی جعبه تکیه نکن.';
let ids=state.need==='charger'?(multi?[238,16]:[1025,238]):state.need==='both'?(multi||device==='laptop'?[244,238]:[1131,1025]):state.priority==='capacity'?[247,1131]:device==='laptop'?[244]:[1131,247];
if(device==='laptop'&&state.need==='charger')ids=[238,240]; return {heading,lead,wires:wires[device],ids,reuse}
}
function renderResult(){const r=resultData();const deviceName=devices.find(d=>d[0]===state.device)[1];wizard.innerHTML='<div class="result-head"><span class="tick">✓</span><div><h3 tabindex="-1">حالا می‌دانی چه چیزهایی را بررسی کنی.</h3><p>'+deviceName+' · '+priorities[state.need].find(p=>p[0]===state.priority)[1]+'</p></div></div><div class="result-summary"><h4>'+r.heading+'</h4><p>'+r.lead+'</p></div><ul class="checklist"><li><b>'+r.wires[0]+' — </b>'+r.wires[1]+'</li><li>برای شارژ خود پاوربانک، مشخصات <b>ورودی</b> را ببین؛ برای شارژ گوشی، مشخصات <b>خروجی</b> را.</li><li>پیش از پرداخت، کابل داخل جعبه و شرایط ضمانت همان نسخه را بررسی کن.</li></ul><div class="result-warning">این‌ها گزینه‌هایی برای بررسی‌اند؛ سازگاری نهایی و سرعت شارژ باید برای مدل دقیق دستگاه و نسخه محصول تأیید شود.</div><div class="mini-products">'+r.ids.map(mini).join('')+'</div><div class="wizard-actions"><button class="back" data-back="3">تغییر اولویت</button><button class="button secondary-btn" data-reset>از اول انتخاب کنم</button></div>'}
wizard.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.start){state={step:2,need:b.dataset.start,device:null,priority:null}}else if(b.dataset.device){state.device=b.dataset.device;state.step=3}else if(b.dataset.priority){state.priority=b.dataset.priority;state.step=4}else if(b.dataset.back){state.step=Number(b.dataset.back)}else if(b.hasAttribute('data-reset')){state={step:1,need:null,device:null,priority:null}}else return;renderWizard()});
const issues={
slow:{title:'شارژ کند، همیشه نشانه خرابی نیست.',intro:'اول کابل و درگاه شارژ را بررسی کن؛ بعد تنظیمات شارژ سریع و دمای گوشی را.',steps:['کابل مناسب و درگاه شارژ سریع را انتخاب کن. در بعضی شارژرها و پاوربانک‌ها، همه درگاه‌ها سرعت یکسانی ندارند.','فقط گوشی را وصل نگه دار و سرعت را دوباره بررسی کن. هنگام شارژ چند دستگاه، توان شارژر یا پاوربانک ممکن است بین آن‌ها تقسیم شود.','اگر گوشی تنظیم شارژ سریع دارد، فعال بودن آن را بررسی کن. گرم شدن گوشی یا نزدیک شدن باتری به شارژ کامل هم می‌تواند سرعت را کاهش دهد.'],source:'https://www.samsung.com/uk/support/mobile-devices/how-to-use-super-fast-charging-on-galaxy-s24-ultra-s24-plus-and-s24/'},
refill:{title:'چرا خود پاوربانک دیر شارژ می‌شود؟',intro:'برای سرعت شارژ شدن پاوربانک، مشخصات ورودی (Input) مهم است؛ عدد خروجی (Output) مربوط به شارژ دستگاه‌های دیگر است.',steps:['روی دستگاه یا دفترچه، بخش Input را ببین. حداکثر ورودی با خروجی ممکن است فرق کند.','توان و پروتکل خروجی کلگی و ظرفیت کابل را با ورودی پاوربانک تطبیق بده. کلگی قوی‌تر از سقف ورودی، الزاماً سریع‌تر نیست.','برای بررسی زمان شارژ، مصرف هم‌زمان از پاوربانک را قطع کن؛ فقط اگر دفترچه همان مدل اجازه شارژ و استفاده هم‌زمان می‌دهد از این قابلیت استفاده کن.'],source:'https://www.anker.com/uk/blogs/power-banks/how-long-does-a-power-bank-take-to-charge'},
capacity:{title:'ظرفیت اسمی، تعداد شارژ قطعی نیست.',intro:'۲۰ هزار تقسیم بر ۵ هزار، معیار دقیق تعداد دفعات شارژ نیست.',steps:['مقایسه انرژی باید ولتاژ و وات‌ساعت را هم در نظر بگیرد. ظرفیت اسمی به‌تنهایی کافی نیست.','تبدیل انرژی و استفاده از گوشی هنگام شارژ، انرژی قابل ذخیره در گوشی را کمتر می‌کند.','اگر افت ناگهانی و شدید درصد یا خالی‌شدن غیرعادی بدون استفاده می‌بینی، تجربه را ثبت کن و با ضمانت‌کننده همان کالا مطرح کن.'],source:'https://service.anker.com/article-description/Why-is-the-Rated-Capacity-of-Power-Banks-Lower-Than-Expected'},
heat:{title:'اگر دستگاه داغ شده، شارژ را موقتاً متوقف کن.',intro:'گرم شدن و افت سرعت می‌تواند به شرایط استفاده و دما مربوط باشد.',steps:['بازی، کار سنگین و قرار گرفتن زیر آفتاب را متوقف کن؛ دستگاه را در محیط خنک‌تر و دارای جریان هوا بگذار.','گوشی را زیر بالش یا پوشش نگه ندار. اگر قاب باعث حبس گرما می‌شود، هنگام شارژ آن را جدا کن.','اگر تورم، بوی غیرعادی، آسیب یا گرمای شدید وجود دارد، استفاده و شارژ را متوقف کن و برای بررسی به خدمات معتبر مراجعه کن.'],source:'https://www.apple.com/batteries/maximizing-performance/'},
disconnect:{title:'کابل و اتصال را قدم‌به‌قدم بررسی کن.',intro:'از ساده‌ترین قسمت شروع کنیم، بدون فشار آوردن به درگاه.',steps:['کابل آسیب‌دیده را کنار بگذار. با یک کابل سالم و سازگار و اتصال محکم دوباره بررسی کن.','برای هندزفری یا ساعت، دفترچه پاوربانک را برای حالت کم‌جریان ببین؛ روش فعال‌سازی در مدل‌ها متفاوت است.','اگر با کابل سالم و پورت مناسب مشکل ادامه داشت، سراغ دفترچه و ضمانت برو. درگاه یا باتری را خودت باز نکن.'],source:'https://www.mi.com/global/support/faq/details/KA-601699/'}
};
let selectedIssue='slow';function showIssue(key){selectedIssue=key;const d=issues[key];document.querySelector('#help-result').innerHTML='<div class="enter"><span class="eyebrow">این سه مورد را به‌ترتیب بررسی کن</span><h3>'+d.title+'</h3><p class="help-intro">'+d.intro+'</p><ol class="help-steps">'+d.steps.map(s=>'<li>'+s+'</li>').join('')+'</ol><a class="source-link" href="'+d.source+'" target="_blank" rel="noopener">راهنمای سازنده</a><div><button class="button secondary-btn" id="help-done">بررسی کردم، هنوز مشکل دارم</button></div></div>';document.querySelectorAll('[data-issue]').forEach(b=>{let on=b.dataset.issue===key;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});document.querySelector('#help-done').onclick=e=>{e.target.parentElement.innerHTML='<p class="done-message" role="status">مدل دستگاه، عکس برچسب ورودی/خروجی و شرح مشکل را آماده کن و با ضمانت‌کننده یا پشتیبانی فروشنده مطرح کن. با این اطلاعات بررسی دقیق‌تر می‌شود.</p>'}};
showIssue('slow');document.querySelectorAll('[data-issue]').forEach(b=>b.onclick=()=>showIssue(b.dataset.issue));
if('IntersectionObserver' in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.care-feature,.tip-card,.section-top,.closing').forEach(el=>io.observe(el))}
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'configure_charge_guide',title:'تنظیم راهنمای شارژ',description:'Configure the visible three-step guide and display guidance; does not purchase or certify compatibility.',inputSchema:{type:'object',properties:{need:{type:'string',enum:['powerbank','charger','both']},device:{type:'string',enum:devices.map(d=>d[0])},priority:{type:'string',enum:['light','capacity','reuse','single','multi']}},required:['need','device','priority'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Object.hasOwn(priorities,input.need)||!devices.some(d=>d[0]===input.device)||!priorities[input.need].some(p=>p[0]===input.priority))throw new Error('ترکیب انتخاب معتبر نیست');state={step:4,need:input.need,device:input.device,priority:input.priority};renderWizard();return {status:'guidance_displayed',...state,compatibility:'requires_exact_model_verification'}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}

