const careGuides={
 iphone:{label:'آیفون ۱۵ و جدیدتر',path:['Settings','Battery','Charging'],option:'Charge Limit',detail:'سقف شارژ را متناسب با نیاز روزانه‌ات انتخاب کن. در نسخه‌های جدید iOS، از ۸۰ تا ۱۰۰ درصد با فاصله‌های ۵ درصدی قابل انتخاب است.',note:'وقتی سقف روی ۱۰۰٪ باشد، گزینه Optimised Battery Charging هم در دسترس است. اگر روز طولانی در پیش داری، لازم نیست خودت را به شارژ ۸۰٪ محدود کنی.',source:'https://support.apple.com/en-ie/108055',image:'iphone-charging.png',caption:'تصویر رسمی اپل • نمونه صفحه در iOS 18؛ ظاهر نسخه‌های دیگر ممکن است متفاوت باشد.'},
 iphone14:{label:'آیفون ۱۴ و قدیمی‌تر',path:['Settings','Battery','Battery Health & Charging'],option:'Optimised Battery Charging',detail:'شارژ بهینه را بررسی کن. گوشی با یادگیری عادت شارژ، ممکن است ادامه شارژ بعد از ۸۰٪ را تا نزدیک زمان استفاده به تأخیر بیندازد.',note:'این گزینه سقف دائمی ۸۰٪ نیست. اگر اعلان شارژ بهینه را دیدی و زودتر به شارژ کامل نیاز داشتی، اعلان را نگه دار و Charge Now را بزن.',source:'https://support.apple.com/en-ie/108055'},
 samsung:{label:'گلکسی با One UI 7 و جدیدتر',path:['Settings','Battery','Battery protection'],option:'Maximum',detail:'در مدل‌های سازگار، حالت Maximum سقف‌های ۸۰، ۸۵، ۹۰ و ۹۵ درصد دارد. سقفی را انتخاب کن که شارژ کافی برای روزت باقی بگذارد.',note:'در بعضی مدل‌ها مسیر از Settings › Device care › Battery می‌گذرد. نام حالت‌ها و امکانات به مدل و نسخه نرم‌افزار بستگی دارد.',source:'https://www.samsung.com/sa_en/support/galaxy-battery/battery-protection-tips/'},
 samsung61:{label:'گلکسی با One UI 6.1',path:['Settings','Battery','Battery protection'],option:'Maximum · 80%',detail:'در این نسخه، حالت Maximum شارژ را در ۸۰٪ متوقف می‌کند. حالت Adaptive محافظت را با الگوی خواب هماهنگ می‌کند.',note:'در نسخه‌های قدیمی‌ترِ سازگار، Protect battery سقف ۸۵٪ دارد. اگر گزینه را پیدا نکردی، نام Battery protection یا Protect battery را در جست‌وجوی تنظیمات وارد کن.',source:'https://www.samsung.com/levant/support/mobile-devices/galaxy-battery-protection-feature-in-one-ui-6-1/'}
};
function setBatteryPhone(phone){
 const d=careGuides[phone];if(!d)return;
 const visual=d.image?'<img class="official-screen" src="assets/'+d.image+'" alt="صفحه Charging آیفون؛ محل انتخاب Charge Limit و گزینه Optimised Battery Charging" width="320" height="660" loading="lazy">':'<div class="phone-diagram" role="img" aria-label="نمای شماتیک مسیر تنظیمات '+d.label+'"><span class="phone-speaker"></span><small dir="ltr">'+d.path[1]+'</small><h4 dir="ltr">'+d.path[2]+'</h4><div class="diagram-battery">▰ ▰ ▰ ▱</div><div class="diagram-option" dir="ltr">'+d.option+'<span>✓</span></div><p>گزینه‌ای که باید بررسی کنی</p></div>';
 document.querySelector('#battery-settings-result').innerHTML='<div class="care-walkthrough enter"><div class="care-instructions"><span class="eyebrow">راهنمای '+d.label+'</span><ol class="care-steps"><li><b>تنظیمات گوشی را باز کن.</b><span dir="ltr">'+d.path[0]+'</span></li><li><b>وارد بخش باتری شو.</b><span dir="ltr">'+d.path[1]+'</span></li><li><b>این بخش را باز کن.</b><span dir="ltr">'+d.path[2]+'</span></li></ol><div class="care-action"><b>حالا کدام گزینه را بررسی کنم؟</b><h4 dir="ltr">'+d.option+'</h4><p>'+d.detail+'</p></div><p class="settings-note">'+d.note+'</p><a class="source-link" href="'+d.source+'" target="_blank" rel="noopener">دیدن راهنمای رسمی سازنده ↗</a></div><figure class="care-screen">'+visual+'<figcaption>'+(d.caption||'نمای شماتیک آموزشی؛ اسکرین‌شات گوشی نیست و جای گزینه‌ها ممکن است متفاوت باشد.')+'</figcaption></figure></div>';
 document.querySelectorAll('[data-care-phone]').forEach(b=>{const active=b.dataset.carePhone===phone;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active))});
}
document.querySelectorAll('[data-care-phone]').forEach(b=>b.addEventListener('click',()=>setBatteryPhone(b.dataset.carePhone)));
setBatteryPhone('iphone');
